"""n_ob

Revision ID: 76fec3c4083b
Revises: b22d43f8fcbc
Create Date: 2019-07-12 10:56:04.762417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fec3c4083b'
down_revision = 'b22d43f8fcbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('n_ob', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'n_ob')
    # ### end Alembic commands ###
